### ISSUE TITLE
Re open the repository. 

### ISSUE THREAD

**Issue by KelvynCore** [pjabardo/Psychro.jl#1]
Please let me work on it, I could add some information. Examples and extend the tool. 

Best,
Kelvyn

**Comment by pjabardo** [comment]
I really need to work on this. Why don't you create a fork and then do a pull request? 
Check out this bitbucket repository: https://bitbucket.org/pjabardo/psychro/
I was initially simply translating that code. Probably better interfaces (and more Julian) are possible.
It is an implementation in C++ with interfaces to R and excel.

By the way I will have to work on this because I intend to create something close to EES (Engineering equation solver) in the next year. So probably I will create a github organization for that and associated code.

**Comment by KelvynCore** [comment]
Thanks!! I'll create the fork and work on it. 

Best,
Kelvyn

**Comment by pjabardo** [comment]
I have been doing some work. Reimplementing the some parts of the code and adding documentation that includes references to where I got the equations from.
 

    Em Sábado, 26 de Agosto de 2017 5:59, Kelvyn Baruc Sánchez Sánchez <notifications@github.com> escreveu:
 

 Thanks!! I'll create the fork and work on it.Best,
Kelvyn—
